### ISSUE TITLE
Brochure site for Scuttlebot

### ISSUE THREAD

**Issue by pfrazee** [ssbc/docs#6]
We should get a simple brochure site up for scuttlebot, something comparable to
- http://reactjs.com
- http://electron.atom.io/
- http://redis.io

We just need something nice that explains the pitch, gives some blurbs about the why, and links out to docs/examples/download.

This may be our chance to put hermies the hermit-crab to work:

![hermies-the-hermit-doodle](https://cloud.githubusercontent.com/assets/1270099/10050515/5f86d4a6-61e2-11e5-90a9-ae97adca690d.jpg) (bottom one)

**Comment by pfrazee** [comment]
tagline proposals:
- "a secure database with replication that is guaranteed to work" (from the ssb repo)
- "secure p2p data feeds"
- "write desktop apps that connect like web apps"

Some of the things we could talk about, for the "why" blurbs:
- Confidentiality. You can write encrypted messages, and the server runs on the user's device. Though hosted software can use Scuttlebot, we've designed it for desktop applications, where nobody tracks your behavior.
- Autonomy. It's decentralized and thin-server. Users can change their applications and peers without losing data. The business logic is in the device, not the network.
- Lightweight semantics. It's a log of typed messages with typed, content-hash links. It's designed for applications to collaborate around data-models, but it doesn't enforce schemas or top-down validation.

who should use it:
- developers looking to build highly-connective desktop applications
- orgs and offices looking for secure sharing that's easy to setup and run
- folks looking for confidentiality on the net
- hackers interested in semantic-web publishing

cc @dominictarr @ahdinosaur @mixmix

**Comment by mixmix** [comment]
what i read _"this is a tool for hackers and developers, we provide guarantees because the reliability might be questioned . it's also good for security and autonomy for a range of technical reasons"_

**who is scuttlebot practically for?** perhaps we can tell this by how they would use it.
- i can see devs using it to build resilient distributed apps
- _I'm unclear how an org or office would practically use it without an interface like patchwork/ phoenix ?)_
- privacy people can't just use scuttlebot ... unless they are starting a pub server to plug existing apps into it ? 
- I don't know enough about semantic web to analyse the last one

---

_Disclaimer: the following is me throw a bunch of ideas out at about 40% quality, just to explore the neighbourhood of ideas ("green hat" in if you know Edward de Bono's thinking hats). I don't even know if some of it is true._

---

**Tagline alternatives** :
- gossip-based network database
- autonomous p2p databases
- secure and resilient distributed-database
- standalone or integrable p2p database-node

**Alternative why's** 
- open protocol-based system : _platforms lock you to companies which might lead to problems around data ownership and privacy. Distributed protocol-based communication avoids this.
- resilience :  _the distributed nature of this network mean it can't be taken down by killing single servers, and it doesn't even need point to point connections to deliver messages. This makes it amazing for disaster situations, or locations with limited connectivity._
- expandable : _the data store is designed to be simple enough that many applications can build on the protocol and interact_

**other thoughts**: 
- the desktop-only thing might be a problem with the rise of mobile. I'm guessing it will need _either_ a phone friendly version _or_ a server that allows interaction with the network via email or something (think about how github has brought git into the mobile realm)
- I like hermes as a mascot name. perhaps he needs winged sandles to make that link clearer though. The greek diety vibe kinda runs across the pirate vibe maybe... anyway, not that relevant. I like the crab :shell:

**Comment by mixmix** [comment]
GRRR, why aren't we using the tool to discuss this.

**Comment by pfrazee** [comment]
Hmm yeah lets not use the term semantic web, it's a bit overloaded at this point

**Comment by ahdinosaur** [comment]
[example in my inbox](https://www.loomio.org/d/Pz6JKCiO/sandstorm-io) of potential users talking about what they want: [sandstorm.io](https://sandstorm.io/).
