### ISSUE TITLE
Is there a better way for creating a client?

### ISSUE THREAD

**Issue by pfrazee** [ssbc/docs#8]
https://github.com/ssbc/docs/blob/master/intro-to-using-sbot.md#create-client

This is the current instructions... @dominictarr I know you're working on this, but is there something immediately better we can do? It's a _bit_ ugly.

**Comment by dominictarr** [comment]
firstly, you shouldn't access deps of deps, that probably won't work with npm@3, if you depend on it, put it in your package.json.

We could probably simplify some of those, or wrap the boiler plate in something...

What is the motivation for easier client setup?

**Comment by pfrazee** [comment]
> What is the motivation for easier client setup?

Just so it looks nicer to newcomers.

**Comment by dominictarr** [comment]
Right, so simpler to document. I think we had a library for that called ssb-client but it got old because we wern't actually using it for anything. If we are documenting something we have to maintain it and we won't maintain it unless we are using it. It would be better to have verbose documentation if we arn't gonna use that way.

**Comment by pfrazee** [comment]
Ok yeah I'll update ssb-client

**Comment by pfrazee** [comment]
Ok done https://github.com/ssbc/ssb-client
